export const ComponentIDs = {
  allClubsMenuItem: 'allClubsMenuItem',
  myClubsMenuItem: 'myClubsMenuItem',
  adminMenuItem: 'adminMenuItem',
  addAdminPermsBtn: 'addAdminPermsBtn',
  changePwOldPw: 'changePwOldPw',
  changePwNewPw: 'changePwNewPw',
  changePwConfirmPw: 'changePwConfirmPw',
  changePwSubmit: 'changePwSubmit',
  basicNavbarNav: 'basicNavbarNav',
  currentUserDropdown: 'currentUserDropdown',
  currentUserDropdownProfile: 'currentUserDropdownProfile',
  currentUserDropdownSignOut: 'currentUserDropdownSignOut',
  homeFormFirstName: 'homeFormFirstName',
  homeFormLastName: 'homeFormLastName',
  homeFormBio: 'homeFormBio',
  homeFormSubmit: 'homeFormSubmit',
  homeMenuItem: 'homeMenuItem',
  loginDropdown: 'loginDropdown',
  loginDropdownSignIn: 'loginDropdownSignIn',
  loginDropdownSignUp: 'loginDropdownSignUp',
  signInFormEmail: 'signInFormEmail',
  signInFormPassword: 'signInFormPassword',
  signInFormSubmit: 'signInFormSubmit',
  signUpFormEmail: 'signUpFormEmail',
  signUpFormPassword: 'signUpFormPassword',
  signUpFormConfirmPassword: 'signUpFormConfirmPassword',
  signUpFormSubmit: 'signUpFormSubmit',
  adminEditor: 'adminEditor',
};

export const PageIDs = {
  addProjectPage: 'addProjectPage',
  profilePage: 'profilePage',
  editProfilePage: 'editProfilePage',
  landingPage: 'landingPage',
  notAuthorizedPage: 'notAuthorizedPage',
  notFoundPage: 'notFoundPage',
  myClubsPage: 'myClubsPage',
  allClubsPage: 'allClubsPage',
  signInPage: 'signInPage',
  signOutPage: 'signOutPage',
  signUpPage: 'signUpPage',
  adminPage: 'adminPage',
};
